version: '3.1'

services:

  db:
    image: postgres
    container_name: postgres_docker
    hostname: postgres_docker
    restart: always
    environment:
      POSTGRES_PASSWORD: pricemonitoring
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer_docker
    hostname: adminer_docker
    restart: always
    ports:
      - 8090:8080

  pricemonitoring:
    image: dcbasso/price-monitoring
    container_name: price-monitoring
    hostname: price-monitoring
    restart: always
    ports:
      - 8080:8080