name: Build and Deploy Docker (Docker Hub)

on:
  push:
    branches:
      - main  # ajuste conforme a branch que deseja monitorar para as alterações

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Temurin JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build project
      run: ./gradlew build
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker buildx build --platform linux/amd64,linux/arm64 -t dcbasso/price-monitoring:latest . --push
