name: Pull Request Workflow (Build and check for failures)

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Temurin JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build project
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker buildx build --platform linux/amd64,linux/arm64 -t dcbasso/price-monitoring:latest -f docker/Dockerfile .

  notify-failure:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ failure() }}

    steps:
      - name: Mark pull request as blocked
        uses: JasonEtco/locked-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reason: "Um dos processos do build falhou. Verifique os logs e corrija o problema antes de mesclar este pull request."
